### PR TITLE
minor cleanup; more idiomatic example/ code

### PR DESCRIPTION
**Pull request by Byron**
While looking into bincode, I thought I could contribute some minor improvements. Thanks for making this fantastic library!

### CODE REVIEW

**Comment by jdm** [comment]
So apparently rust 1.18 doesn't like the `&dyn` syntax. That's a version of Rust that was released in 2017; I wonder if it's time to update the minimum supported Rust version yet...

**Comment by Byron** [comment]
Oh, that is surprising! I would have expected the (recent) Rust compiler to not complain about things prior to edition 2018.

If this project wishes to maintain Rustc v1.18 compatibility, it's probably best to close this PR. 

Alternatively it would be worth re-evaluating which Rust version now is suitable - it's probably depending mostly on this crate's consumers.

Please feel free to do whatever you find appropriate.

**Comment by ZoeyR** [comment]
For 1.0 crates I've always been of the opinion that bumping the msrv is a breaking change.

**Comment by Byron** [comment]
I am closing the PR as it probably can't be merged in the current form.

**Pull request closed without merging**
